# Generated by Django 5.0.3 on 2024-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalcontact_remove_spamreport_is_spam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontact',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
