# Generated by Django 5.0.3 on 2024-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_globalcontact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontact',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
